### ISSUE TITLE
Bugs in LCM/GCD scalar functions (found by SQLancer)

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#11031]
### Describe the bug

1. It should return an error instead of crash
```shell
> SELECT LCM(9223372036854775807, -9223372036854775808);
thread 'main' panicked at /arrow-datafusion/datafusion/functions/src/math/gcd.rs:112:9:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

DataFusion CLI v39.0.0
> SELECT GCD(9223372036854775807, -9223372036854775808);
thread 'main' panicked at /arrow-datafusion/datafusion/functions/src/math/gcd.rs:112:9:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2. This query get stuck for really long time, but same query in duckdb can return immediately
```shell
DataFusion CLI v39.0.0
> select GCD(-9223372036854775808, 1);
^C

DataFusion CLI v39.0.0
> select LCM(-9223372036854775808, 1);
^C
```

Found by very initial implementation of SQLancer https://github.com/apache/datafusion/issues/11030

**Comment by LorrensP-2158466** [comment]
take
