### ISSUE TITLE
`SanityCheckPlan` failed on `sql_planning`1 benchmark: , Plan("Child: [\"ProjectionExec: expr=[]\", \"  CoalesceBatchesExec: target_batch_size=8192\", 

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11322]
### Describe the bug

The `SanityCheckPlan` pass (added in https://github.com/apache/datafusion/pull/11196) is now failing when I run `cargo bench --bench sql_planner` to test planning speed

### To Reproduce

Run this command
```shell
RUST_BACKTRACE=1 cargo bench --profile dev --bench sql_planner physical_plan_tpcds_all
```

Here is the output:
```
Benchmarking physical_plan_tpcds_all: Warming up for 3.0000 sthread 'main' panicked at datafusion/core/benches/sql_planner.rs:49:14:
called `Result::unwrap()` on an `Err` value: Context("SanityCheckPlan", Plan("Child: [\"ProjectionExec: expr=[]\", \"  CoalesceBatchesExec: target_batch_size=8192\", \"    FilterExec: r_reason_sk@0 = 1\", \"      MemoryExec: partitions=0, partition_sizes=[]\"] does not satisfy parent distribution requirements: SinglePartition"))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1077:23
   4: sql_planner::physical_plan::{{closure}}
             at ./benches/sql_planner.rs:44:9
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
   6: tokio::runtime::coop::with_budget
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
   9: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  11: tokio::runtime::context::runtime::enter_runtime
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  13: tokio::runtime::runtime::Runtime::block_on
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
  14: sql_planner::physical_plan
             at ./benches/sql_planner.rs:43:26
  15: sql_planner::criterion_benchmark::{{closure}}::{{closure}}
             at ./benches/sql_planner.rs:211:17
  16: criterion::bencher::Bencher<M>::iter
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/bencher.rs:88:23
  17: sql_planner::criterion_benchmark::{{closure}}
             at ./benches/sql_planner.rs:209:9
  18: criterion::benchmark_group::BenchmarkGroup<M>::bench_function::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/benchmark_group.rs:254:60
  19: <criterion::routine::Function<M,F,T> as criterion::routine::Routine<M,T>>::warm_up
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/routine.rs:270:13
  20: criterion::routine::Routine::sample
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/routine.rs:147:38
  21: criterion::analysis::common
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/analysis/mod.rs:83:22
  22: criterion::benchmark_group::BenchmarkGroup<M>::run_bench
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/benchmark_group.rs:320:21
  23: criterion::benchmark_group::BenchmarkGroup<M>::bench_function
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/benchmark_group.rs:254:9
  24: criterion::Criterion<M>::bench_function
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/lib.rs:1220:9
  25: sql_planner::criterion_benchmark
             at ./benches/sql_planner.rs:208:5
  26: sql_planner::benches
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/macros.rs:71:17
  27: sql_planner::main
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/macros.rs:124:17
  28: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: bench failed, to rerun pass `-p datafusion --bench sql_planner`
(venv) andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion2$
```

### Expected behavior

The benchmark should complete without error

**Comment by ozankabak** [comment]
We will check and fix tomorrow

**Comment by berkaysynnada** [comment]
The problem is in tpc-ds/9. The issue arises because `NestedLoopJoinExec` requires SinglePartition from the left side, but MemoryExec sends 0 partitions. We will discuss a rational solution and submit a fixing PR.
