### ISSUE TITLE
Test Rust 2024 Edition

### ISSUE THREAD

**Issue by crepererum** [apache/datafusion#13631]
# What
Follow ["Rust 2024 call for testing"](https://blog.rust-lang.org/2024/11/27/Rust-2024-public-testing.html).

# Why
Apache DataFusion is a non-trivial project and we can provide valuable input for the compiler team.

# How
See blog post. Report any issues that are encountered.

**Comment by Omega359** [comment]
I did a quick test using 

cargo fix --edition and there are a lot of concerns with drop ordering and if let scoping:

```
warning: `if let` assigns a shorter lifetime since Edition 2024
    --> datafusion/common/src/scalar/mod.rs:1861:28
     |
1861 |                         if let ScalarValue::$SCALAR_TY(v) = sv {
     |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^--
     |                                                             |
     |                                                             this value has a significant drop implementation which may observe a major change in drop order and requires your discretion
...
1937 |             DataType::Int32 => build_array_primitive!(Int32Array, Int32),
     |                                ----------------------------------------- in this macro invocation
     |
     = warning: this changes meaning in Rust 2024
     = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/temporary-if-let-scope.html>
```

```
warning: relative drop order changing in Rust 2024
    --> datafusion/expr/src/utils.rs:1144:32
     |
1144 |         while let Some(expr) = stack.pop() {
     |                        ----    ^^^^^^^^^^^
     |                        |       |
     |                        |       this value will be stored in a temporary; let us call it `#2`
     |                        |       up until Edition 2021 `#2` is dropped last but will be dropped earlier in Edition 2024
     |                        `expr` calls a custom destructor
     |                        `expr` will be dropped later as of Edition 2024
...
1147 |                     right,
     |                     -----
     |                     |
     |                     `right` calls a custom destructor
     |                     `right` will be dropped later as of Edition 2024
1148 |                     op: Operator::And,
1149 |                     left,
     |                     ----
     |                     |
     |                     `left` calls a custom destructor
     |                     `left` will be dropped later as of Edition 2024
...
1154 |                 Expr::Alias(Alias { expr, .. }) => stack.push(*expr),
     |                                     ----
     |                                     |
     |                                     this value will be stored in a temporary; let us call it `#1`
     |                                     `#1` will be dropped later as of Edition 2024
...
1157 |         }
     |         - now the temporary value is dropped here, before the local variables in the block or statement
```

It's not going to be a quick migration. 2024 also required <= 1.85.0 so Datafusion couldn't use it until 1.89.0 is released according to the MSRV policy.

**Comment by crepererum** [comment]
Is the drop order an actual issue in practice or just a warning regarding a behavior change? Esp. does DataFusion compile after `cargo fix ...`?

**Comment by Omega359** [comment]
I don't know if the warning is a concern or not. I suspect someone will have to look at them all the determine that. There was a number of other changes too that will have to be looked into including a [renaming of $expr to $expr_2021](https://doc.rust-lang.org/edition-guide/rust-2024/macro-fragment-specifiers.html) which likely in almost all cases could be undone.

I didn't try a compile afterwards but I suspect it wouldn't compile.

**Comment by crepererum** [comment]
# Test Report

## Steps
See <https://blog.rust-lang.org/2024/11/27/Rust-2024-public-testing.html>.

### 1. Install the most recent nightly with `rustup update nightly`.
No Problem.

### 2. In your project, run `cargo +nightly fix --edition`.
Same as https://github.com/apache/datafusion/issues/13631#issuecomment-2659449432 , but I don't think these warnings are actually a problem for us. I doubt that most people really pay attention to the drop order in these scenarios anyways.

### 3. Edit `Cargo.toml` and change the edition field to say `edition = "2024"` and, if you have a `rust-version` specified, set `rust-version = "1.85"`.
Done.

### 4. Run `cargo +nightly check` to verify your project now works in the new edition.
Had to fix:

```text
error: unnecessary qualification
   --> datafusion/core/src/execution/context/mod.rs:661:54
    |
661 | ...                   as std::pin::Pin<Box<dyn futures::Future<Output = _> + Send>>)
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: requested on the command line with `-D unused-qualifications`
help: remove the unnecessary path segments
    |
661 -                             as std::pin::Pin<Box<dyn futures::Future<Output = _> + Send>>)
661 +                             as std::pin::Pin<Box<dyn Future<Output = _> + Send>>)
    |

error: could not compile `datafusion` (lib) due to 1 previous error
```

### 5. Run some tests, and try out the new features!
Ran `cargo +nightly test --all-targets --workspace`. Found the following failures:

```text
thread 'main' panicked at datafusion/core/benches/map_query_sql.rs:86:18:
called `Result::unwrap()` on an `Err` value: Execution("map key must be unique, duplicate key found: 3889")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: test failed, to rerun pass `-p datafusion --bench map_query_sql`
```

(also exists on `main`)

```text
thread 'main' panicked at datafusion/functions/benches/cot.rs:38:64:
called `Result::unwrap()` on an `Err` value: NotImplemented("Function cot does not implement invoke but called")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: test failed, to rerun pass `-p datafusion-functions --bench cot`
```

(also exists on `main`)

```text
thread 'main' panicked at datafusion/functions/benches/isnan.rs:37:63:
called `Result::unwrap()` on an `Err` value: NotImplemented("Function isnan does not implement invoke but called")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: test failed, to rerun pass `-p datafusion-functions --bench isnan`
```

(also exists on `main`)

This is where I stopped. It's annoying that our tests don't run with the default feature set. I don't have the time to fix that. Overall though things compile and I expect the edition to not really regress things.

## Summary
Once our MSRV reaches 1.85, I think we're good to go 🚀

**Comment by Jefffrey** [comment]
Given 2024 edition has now released, I'll close this issue in favour of #15804 which is explicitly about upgrading to 2024, and not just testing it.
