### ISSUE TITLE
`ScalarValue::to_array` panics when getting statistics for List<Struct> column 

### ISSUE THREAD

**Issue by trueleo** [apache/datafusion#5706]
### Describe the bug

When querying a parquet file, Datafusion panics if schema provided to `ListingTable`  contains a column of type List\<Struct\> which is not present in the file itself. It does not panic when `collect_stats` option is set to false.

Backtrace 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ArrowError(ComputeError("concat requires input of at least one array"))', /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-common-20.0.0/src/scalar.rs:1919:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1113:23
   4: datafusion_common::scalar::ScalarValue::to_array_of_size
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-common-20.0.0/src/scalar.rs:1911:22
   5: datafusion_common::scalar::ScalarValue::to_array
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-common-20.0.0/src/scalar.rs:1261:9
   6: datafusion::datasource::get_statistics_with_limit::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/datasource/mod.rs:96:56
   7: datafusion::datasource::listing::table::ListingTable::list_files_for_scan::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/datasource/listing/table.rs:784:67
   8: <datafusion::datasource::listing::table::ListingTable as datafusion::datasource::datasource::TableProvider>::scan::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/datasource/listing/table.rs:641:60
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  10: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/physical_plan/planner.rs:485:88
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  12: <datafusion::physical_plan::planner::DefaultPhysicalPlanner as datafusion::physical_plan::planner::PhysicalPlanner>::create_physical_plan::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/physical_plan/planner.rs:423:21
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  14: <datafusion::execution::context::DefaultQueryPlanner as datafusion::execution::context::QueryPlanner>::create_physical_plan::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/execution/context.rs:1160:13
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/future/future.rs:124:9
  16: datafusion::execution::context::SessionState::create_physical_plan::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/execution/context.rs:1993:13
  17: datafusion::dataframe::DataFrame::create_physical_plan::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/dataframe.rs:99:60
  18: datafusion::dataframe::DataFrame::collect::{{closure}}
             at /home/trueleo/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-20.0.0/src/dataframe.rs:685:47
  19: datafusion_list_check::query::run::{{closure}}
             at ./src/main.rs:52:30
  20: datafusion_list_check::main::{{closure}}
             at ./src/main.rs:65:17
```

### To Reproduce

Wrote a small program to reproduce this issue.  https://gist.github.com/rust-play/ab9bcac4290e04f243eb02a93670751c

### Expected behavior

Query should not panic when collecting stats for column that does not exist in the parquet file.

**Comment by trueleo** [comment]
This is the unwrap 
https://github.com/apache/arrow-datafusion/blob/3e247958b1dc30b67b309f712be75f3c725d427e/datafusion/common/src/scalar.rs#L2277-L2285
